name       : dhewm3
version    : 1.5.0
release    : 4
homepage   : https://dhewm3.org
source     :
    - https://github.com/dhewm/dhewm3/releases/download/1.5.0/dhewm3-1.5.0-src.tar.xz : fb4b3382f482ef592aaae31f6064f321fc163f9a32b42cd743b87c650e0aad36
license    : GPL-3.0-or-later
component  : games.action
summary    : dhewm 3 is a Doom 3 GPL source port
description: |
    dhewm 3 is a Doom 3 GPL source port
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja -DDEDICATED=1 -S../neo
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/dhewm3.desktop $installdir/usr/share/applications/dhewm3.desktop
    install -Dm00644 $pkgfiles/dhewm3-dedicated.desktop $installdir/usr/share/applications/dhewm3-dedicated.desktop
    install -Dm00644 $pkgfiles/dhewm3-roe.desktop $installdir/usr/share/applications/dhewm3-roe.desktop
    install -Dm00644 neo/sys/linux/setup/image/doom3.png $installdir/usr/share/pixmaps/doom3.png
    install -Dm00644 neo/sys/aros/ROE.png $installdir/usr/share/pixmaps/doom3-roe.png
