name       : dhewm3
version    : 1.5.2
release    : 10
homepage   : https://dhewm3.org
source     :
    - https://github.com/dhewm/dhewm3/releases/download/1.5.2/dhewm3-1.5.2-src.tar.xz : a6aa31f240e3220fef5e9b80cfe584f9261525f666ed5f513b2b755e7ae0e082
license    : GPL-3.0-or-later
component  : games.action
summary    : dhewm 3 is a Doom 3 GPL source port
description: |
    dhewm 3 is a Doom 3 GPL source port
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
setup      : |
    %cmake_ninja \
        -DDEDICATED=ON \
        -DREPRODUCIBLE_BUILD=ON \
        -Sneo
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/dhewm3.desktop $installdir/usr/share/applications/dhewm3.desktop
    install -Dm00644 $pkgfiles/dhewm3-roe.desktop $installdir/usr/share/applications/dhewm3-roe.desktop
    install -Dm00644 neo/sys/linux/setup/image/doom3.png $installdir/usr/share/pixmaps/doom3.png
    install -Dm00644 neo/sys/aros/ROE.png $installdir/usr/share/pixmaps/doom3-roe.png
