name       : dhewm3
version    : 1.5.1
release    : 7
homepage   : https://dhewm3.org
source     :
    - https://github.com/dhewm/dhewm3/releases/download/1.5.1/dhewm3-1.5.1-src.tar.xz : 31671f35fb6f83272dfa2a27c0dad6183bc228f1f1a448ef925052cf4dcf4b68
license    : GPL-3.0-or-later
component  : games.action
summary    : dhewm 3 is a Doom 3 GPL source port
description: |
    dhewm 3 is a Doom 3 GPL source port
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja \
        -DDEDICATED=ON \
        -DREPRODUCIBLE_BUILD=ON \
        -S../neo
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/dhewm3.desktop $installdir/usr/share/applications/dhewm3.desktop
    install -Dm00644 $pkgfiles/dhewm3-roe.desktop $installdir/usr/share/applications/dhewm3-roe.desktop
    install -Dm00644 neo/sys/linux/setup/image/doom3.png $installdir/usr/share/pixmaps/doom3.png
    install -Dm00644 neo/sys/aros/ROE.png $installdir/usr/share/pixmaps/doom3-roe.png
