name       : dhewm3
version    : 1.4.1
release    : 1
source     :
    - https://github.com/dhewm/dhewm3/archive/1.4.1.tar.gz : 587586142d863ff98051619f0d49c056c5302e919c655a50af69a8293bc3ae08
license    : GPL-3.0
component  : games.action
summary    : dhewm 3 is a Doom 3 GPL source port
description: |
    dhewm 3 is a Doom 3 GPL source port
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - libjpeg-turbo-devel
setup      : |
    cd neo
    %cmake -DDEDICATED=1 .
build      : |
    cd neo
    %make
install    : |
    cd neo
    %make_install
    install -D -m 00644 $pkgfiles/dhewm3.desktop $installdir/usr/share/applications/dhewm3.desktop
    install -D -m 00644 $pkgfiles/dhewm3-dedicated.desktop $installdir/usr/share/applications/dhewm3-dedicated.desktop
